-- Seed data for igp_states (India states + union territories)
INSERT INTO igp_states (name, iso_code, sort_order) VALUES
  ('Andhra Pradesh', 'AP', 10),
  ('Arunachal Pradesh', 'AR', 20),
  ('Assam', 'AS', 30),
  ('Bihar', 'BR', 40),
  ('Chhattisgarh', 'CG', 50),
  ('Goa', 'GA', 60),
  ('Gujarat', 'GJ', 70),
  ('Haryana', 'HR', 80),
  ('Himachal Pradesh', 'HP', 90),
  ('Jharkhand', 'JH', 100),
  ('Karnataka', 'KA', 110),
  ('Kerala', 'KL', 120),
  ('Madhya Pradesh', 'MP', 130),
  ('Maharashtra', 'MH', 140),
  ('Manipur', 'MN', 150),
  ('Meghalaya', 'ML', 160),
  ('Mizoram', 'MZ', 170),
  ('Nagaland', 'NL', 180),
  ('Odisha', 'OD', 190),
  ('Punjab', 'PB', 200),
  ('Rajasthan', 'RJ', 210),
  ('Sikkim', 'SK', 220),
  ('Tamil Nadu', 'TN', 230),
  ('Telangana', 'TS', 240),
  ('Tripura', 'TR', 250),
  ('Uttar Pradesh', 'UP', 260),
  ('Uttarakhand', 'UK', 270),
  ('West Bengal', 'WB', 280),
  ('Andaman and Nicobar Islands', 'AN', 290),
  ('Chandigarh', 'CH', 300),
  ('Dadra and Nagar Haveli and Daman and Diu', 'DN', 310),
  ('Delhi (NCT)', 'DL', 320),
  ('Jammu and Kashmir', 'JK', 330),
  ('Ladakh', 'LA', 340),
  ('Lakshadweep', 'LD', 350),
  ('Puducherry', 'PY', 360)
ON DUPLICATE KEY UPDATE
  name = VALUES(name),
  sort_order = VALUES(sort_order),
  status = 'active';
